spring:
  application:
    name: inspection #应用名称
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1086fgg6d76f4yqco.mysql.rds.aliyuncs.com:3306/service_base
    username: mysql_rw
    password: 3301994411ZQzqZQ

  freemarker:
    enabled: true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    suffix: .ftl


server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads:  1500
    max-connections: 10000


logging:
  config: classpath:logback.xml

swagger:
  production: false
  basic:
    enable: true


login:
  accept:
    urls: /user/login
  replace: false





# 一些额外的功能 可开可不开
support:
  oss:
    enable: true
    accessKeyId: LTAI5tLYA4jUSkbL7uKdW8Q5
    accessKeySecret: vVCPVbP6QI2j1yOG0wSeIRklRLsry3
  redis:
    cluster:
      enable: true
      expire-seconds: 120
      command-timeout: 5000
      nodes: 47.110.48.233:6379,47.110.48.233:6380,47.110.48.233:6381,47.110.48.233:6382,47.110.48.233:6383,47.110.48.233:6384
      max-redirects: 3
      password: qinghe